# fly.toml app configuration file generated for flat-rental-agent on 2024-09-03T21:22:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flat-rental-agent'
primary_region = 'waw'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
